openfaas/workshop

- README.md
> Add VSCode to the list of requirements

- lab2.md
Signed-off-by: Stefan Prodan <stefan.prodan@gmail.com>
> Added OpenFaaS Grafana deploy instructions to Lab 2

- lab7.md
> [WIP] Update Lab 7 with GitHub issues analysis function

- appendix.md
- lab2.md
- lab5.md
- lab6.md
- lab7.md
Signed-off-by: Alex Ellis (VMware) <alexellis2@gmail.com>
* Review / update with Stefan
* Moved some content to appendix
> Review / update moving some content to appendix

- lab7.md
> Update Lab 7 with pictures, fixes and more details

- lab7.md
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>
After walking through this lab, I found a couple of places that could use a little update.
Nothing major, just some wording to help avoid confusion.
> update lab 7 after a fresh walkthrough

- lab5.md
> Fix gateway synchronous route

- lab3.md
> Fix port in Lab 3

- lab3.md
Add a step to pull new templates before being able to create a new function
> Add faas template pull

- lab6.md
> Fix py syntax in Lab 6

- lab3.md
- lab4.md
- lab5.md
> Add image prefix for new functions

- lab3.md
> Add image prefix description

- lab7.md
> Update Lab 7 with error handling in issue-bot

- lab3.md
- lab4.md
- lab7.md
> Make python3 default

- lab2.md
- lab3.md
- lab4.md
- lab7.md
> Update gateway information

- README.md
- lab2.md
Fixed the Lab 2 title to use the active tense as mentioned in https://github.com/openfaas/workshop/pull/28#discussion_r178965235
> Fixed Lab 2 title

- lab4.md
> Add testing combined output to Lab 4

- lab4b.md
Currently this is only going to show a blank page because it's not returning anything from the handler. Hence, added the return statement.
Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>
> Fixed missing return statement

- lab2.md
- lab3.md
This PR is to update the lines in Lab 2 and Lab 3 that mention the Gateway endpoint. The different options that users have for how to specify their gateway endpoint is made more clear.
> Update messaging on specifying a different gateway endpoint

- issue-bot/bot-handler/handler.py
- lab10.md
I fix secrets path that are outdated and misleading.
> Fix couple of misleading and outdated secrets paths

- README.md
Add a link to the top README.md to go to the Japanese version of the
workshop.
Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>
> Add link to Japanese translation

- lab9.md
Swapping nodeinfo with figlet function from store for the scaling
demo
Closes #80 
> Swap nodeinfo for figlet in lab9

- hmac-protected/hmac-protected/handler.py
- hmac-protected/stack.yml
- lab11.md
Adding `lab11` which explains how to use HMAC to validate
the payload of your functions
Closes #61 
> Add lab11 with HMAC validation

- lab4.md
- lab6.md
This updates Labs 4 and 6 to show how a function can be used with
path parameters
Closes #60
> Add Http_Path instructions

- hmac-protected/hmac-protected/handler.py
- lab11.md
- lab6.md
Adressing issues from @padiazg also adding small changes
to the lab11 like changing name from `clearHash` to `getHash`
and adding `python` `yml` and `bash` to the code snippets
Closes #84 
Closes #83 
> Add small fixes to lab6 and lab11

- lab9.md
This adds instructions how to test scale from 0 and how to use
faas-idler as well
Closes #62
> Add scale from zero to Lab 9

- lab5.md
> Fix spelling mistake in lab5

- README.md
- lab1.md
- lab10.md
- lab11.md
- lab1a.md
- lab1b.md
- lab2.md
- lab3.md
- lab4.md
- lab5.md
- lab7.md
- lab9.md
This PR fixes #112  by merging master and kubernetes-preview together into one branch.
> Merge master and kubernetes-preview together to one branch to fix #112

- README.md
Signed-off-by: Magnus Wahlstrand <magnus.wahlstrand@gmail.com>
> Update Tear down/clear link

- README.md
> Move lab1 link to the end of the list of labs

- lab1.md
- lab1b.md
Improve instructions for DO, GKE and for obtaining a gateway
URL.
Signed-off-by: Alex Ellis <alexellis2@gmail.com>
> Update instructions for Kubernetes

- lab1b.md
- use gcloud to create the cluster and the cluster role binding
> Change the GKE instructions to use gcloud CLI

- lab1b.md
> Fixes for openfaas installation steps on kubernetes

- lab1b.md
> Add openfaas login steps and instructions

- lab3.md
> Update lab 3 to fix small issues

- lab1b.md
- lab8.md
Signed-off-by: Edward Wilde <ewilde@gmail.com>
> Clarify external ip & typo

- lab1.md
- lab1b.md
- removes kail
- installs latest kubectl at the start
Signed-off-by: Alex Ellis <alexellis2@gmail.com>
> Update steps for Windows

- lab2.md
- lab3.md
- lab4.md
- lab5.md
I was running through the workshop instructions using vscode in browser and these changes fixes some of the issues that I faced.
> Update workshop instructions

- lab3.md
> Update some instructions from lab3

- lab8.md
Add paragraph on how to change the read_timeout and write_timeout on API Gateway in K8S in the Lab8.
> Add paragraph on how to change the read_timeout and write_timeout

- lab3.md
- translations/ja/lab3.md
Update `faas-cli new --list` command in lab3.
- Update list of available language templates
- Remove the paragraph at the end
```
Or alternatively create a folder containing a Dockerfile, then pick
the "Dockerfile" lang type in your YAML file.
```
> Update `faas-cli new --list` command in lab3

- lab8.md
As discussed with @alexellis on Slack, golang times are used for timeouts.
You cannot use "5", you are forced to use "5s".
I tested it locally and discussed with @alexellis on slack.
> Use golang for timeouts in lab8

- lab1b.md
K3d start new cluster workflow is outdated
Tutorial should be updated to not frustrate people
I tested it locally according correct workflow in [k3d repo](https://github.com/rancher/k3d). It works
Change lab1b description
> Update start k3d cluster workflow

- lab1.md
- lab10.md
- lab2.md
- lab3.md
- lab4.md
- lab5.md
- lab7.md
- lab8.md
- lab9.md
Fixes issue #192 
- [ X] Bug fix (non-breaking change which fixes an issue)
> Removed Docker Swarm references

- README.md
> Fix broken GH sponsor link in README
