openfaas/workshop

- lab3.md
- lab4.md
- lab5.md
- lab6.md
- lab7.md
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>
Standardized all uses of `faas` alias to use the default `faas-cli` command
> changed all faas examples to faas-cli

- lab4b.md
Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>
This lab adds the following sections:
* Generate and return basic HTML from a function
* Read and return a static HTML file from disk
* Read the query string and return different HTML
* Collaborating with other functions
You can learn how to serve HTML from functions and at the end, call
functions via AJAX and render the results in the HTML.
As I talked with Alex, I think this Lab fits well after the environment variables section in Lab 4.
What I'm not sure about yet is whether to change the lab numbers or make this lab something like Lab 4b and change the links inside Lab 4. Changing all the numbers after Lab 5 has some impact and may generate human errors on the way.
> Added "HTML for your functions" lab

- astronaut-finder/handler.py
- hello-openfaas/handler.py
- issue-bot/bot-handler/handler.py
- lab3.md
- lab4.md
- lab5.md
- lab8.md
Signed-off-by: rgee0 <richard@technologee.co.uk>
During the reordering of the labs a number of the code snippets were converted from showing `print(str)` to `return str` to better align with the current template pattern.  This change addresses the remaining items in that regard and also converts cases where errors were being printed before sys.exit(1) was being called.  When anything other than `None` or `0` passed in to sys.exit()  the value is passed out to stderr and a exit code of 1 is returned; this means that separate print and sys.exit statements are unnecessary.
> Convert remaining print() statements to return

- issue-bot-secrets/bot-handler/handler.py
- lab10.md
With this change secret path is updated from `/run/secrets/auth-token` to `/var/openfaas/secrets/auth-token`.
It also adds note for creating auth-token when a remote gateway is used.
Resolves [#49](https://github.com/openfaas/workshop/issues/49)
> Update secret path

- lab10.md
- lab3.md
- lab4.md
- lab5.md
- lab6.md
This change replaces
```
faas-cli build && \
faas-cli push && \
faas-cli deploy
```
with the cmd optimized alternative `faas-cli up`.
Still left build, push and deploy on some places to show we have
these commands as well
Closes #59
> Update with `faas-cli up`

- translations/ja/README.md
- translations/ja/appendix.md
- translations/ja/lab1.md
- translations/ja/lab10.md
- translations/ja/lab2.md
- translations/ja/lab3.md
- translations/ja/lab4.md
- translations/ja/lab5.md
- translations/ja/lab6.md
- translations/ja/lab7.md
- translations/ja/lab8.md
- translations/ja/lab9.md
This is the Japanese version of the OpenFaaS workshop.
The following version(commit) is translated to Japanese.
df8d19b737f399cdfad8985f1ad664b63d2108f9
This workshop has been tested by many users in Japan via a workshop event and is ready to be merged.
The following commits aren't applied yet but will follow  shortly:
* f27ff19c87b0933c51799586d83d5e75cbd78eb2
* 8d91b6407b32fd1c72b0e44406ae12cb67b19b8f
The labs are inside `translations/ja`. Only the labs and not the example codes because it'll be cumbersome to manage both versions.
Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>
> Add initial Japanese version of the OpenFaaS workshop

- lab1.md
A recent issue (openfaas/faas#898)  was raised because a user could not access the gateway on a Windows 10 machine.  The provided detail suggested that the OpenFaaS containers were all showing 0 replicas, which has previously been caused by users not selecting Linux containers in the Windows menu.
This change to Lab 1 adds a note alongside the installation step to ensure that Linux mode is selected.
> Add note to ensure Linux containers are being used

- lab5.md
Adding final field to lab5 just before moving on to lab6
to point how to validate your payload using HMAC
with lab11
Needs #67 to be merged
> Add hmac validation pointing to lab11

- README.md
- lab1.md
Experience has shown that multiple attendees trying to download the system images during the workshop can be temperamental where the establishments WiFi is under high load.  This change introduces a pre-pull command to Lab 1 that attendees should run prior to attending.  The pre-reqs preamble in the README has also been changed to further emphasize that the pre-reqs/lab 1 should be addressed prior to attending.
Resolves #56 
> Add images pre-pull command to lab 1

- lab10.md
- lab11.md
Updated Kubernetes-preview branch to use OpenFaaS secrets as required by #95
> OpenFaas secrets Kubernetes-preview branch

- lab10.md
Fixes #99
Amends the notes around secrets in lab 10 to remove references to creating on the nodes now that secrets can be deployed remotely via the CLI.  The initial note is now more explicit about the format that should be used, DNS1123, rather than simply disallowing underscores.  
The latter note now helpfully reminds that the -g flag can be used with the faas-cli secret commands in order to switch between remote gateways.
> Amend lab10 secrets notes

- translations/ja/lab10.md
Hi, Thank you for awesome workshop 👍
I found that link of `translations/ja/lab10.md` is wrong.
Fixed a little :)
> Fixed link of "translations/ja/lab10.md"

- lab9.md
Swarm and k8s commands were using different functions.  This makes them the same, nodeinfo.
> Change Lab9 k8s function to nodeinfo

- translations/ja/lab10.md
- translations/ja/lab3.md
- translations/ja/lab4.md
- translations/ja/lab5.md
- translations/ja/lab6.md
Original version commans were updated so Japanese version should also be updated.
> Update Japanese version commands

- lab4.md
Trivial change to add file parameter to the faas-cli up command in the narrative. Being explicit should be easier to follow for newer users.
Fixes #135
> Add file param to `faas-cli up` command in lab 4

- lab3.md
Added an additional optional step to demonstrate the environment
variable substitution feature in the yml files with a real-world
use case as an example scenario
The resolves #140 
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>
> Add envsubst steps to lab 3

- lab7.md
- translations/ja/lab7.md
Hey there 👋 
Request Bin moved to https://requestbin.com, this PR fixes the URLs used in the lab7.
> Fix requestbin URL in lab7

- lab7.md
Add note to requestbin.com details that explains the user should uncheck the Private checkbox in order to save them the effort of logging in.
On first trip through I didnt spot it and was prompted to log in.
Trivial text change
> Add note to uncheck the private box on requestbin

- lab1.md
- lab1a.md
- lab1b.md
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
Add [k3sup](https://k3sup.dev/) installation instructions for OpenFaaS
k3sup is a prototype of "faas-cli install" and makes the
experience much easier for newcomers. The longer, manual, and
more detailed instructions are retained in the documentation.
Advanced users are welcome to follow them.
`k3sup` has been tested by the community and in several blog posts on https://blog.alexellis.io/
> Add k3sup instructions

- lab1a.md
The faas-cli login section on swarm was just saying
"use the printed command" rather than outlining what
each section does like the k8s lab shows.
closes #141 
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
#141 
Docs update
> Update the swarm lab 1a for more info on login command

- lab7.md
Signed-off-by: Andreas Amstutz <andreasamstutz@gmail.com>
The current link target does not lead to reference for callback request headers.
I followed the updated link to the reference.
> Update the link target to reference 'Callback request headers' section

- lab7.md
Trivial change that was highlighted in https://github.com/openfaas/workshop/pull/136 to remove a stray backtick within a code block.
Outstanding item from previous PR
One character being removed
> Remove stray backtick in lab 7

- lab1a.md
- lab2.md
kubectl 1.18 changed run to create only a pod, not a pod wrapped in a deployment
> Waterdrips fix lab2

- lab11.md
- lab7.md
- translations/ja/lab5.md
Lab 7: fixed a typo by removing a back tick in a k8s command
Lab 11: updated link to Lab 5
Lab 5 (Japanese version): fixed broken image links
Changes will make labs more correct and easier to follow.
Fixes issues #161 #164 #163 
I was able to click to images from my VS Code IDE, as well as go to the correct Lab 5 link.
> Make minor fixes to openfaas workshop labs

- lab1b.md
Address for arkade is https://get.arkade.dev
and not https://dl.get-arkade.dev/
See official arkade github:
> update address for arkade (see #216)
